name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: gha-demo  
jobs:
  test:
    env:
      MONGODB_DB_NAME: gha-demo
      MONGODB_CLUSTER_ADDRESS: udemy-project.ei1fss4.mongodb.net
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: aPMewxB5lVktnHui
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{env.MONGODB_USERNAME}}
          echo "MONGODB_DB_NAME: $MONGODB_USERNAME
